### ISSUE TITLE
traceback when run in python3

### ISSUE THREAD

**Issue by alkarp** [batfish/ansible#85]
Getting python traceback as following:

`
{
    "module_stdout": "",
    "module_stderr": "Traceback (most recent call last):\n  File \"/var/lib/awx/.ansible/tmp/ansible-local-31cdebbdf/ansible-tmp-1572372537.375614-50462794487074/AnsiballZ_bf_session.py\", line 114, in <module>\n    _ansiballz_main()\n  File \"/var/lib/awx/.ansible/tmp/ansible-local-31cdebbdf/ansible-tmp-1572372537.375614-50462794487074/AnsiballZ_bf_session.py\", line 106, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/var/lib/awx/.ansible/tmp/ansible-local-31cdebbdf/ansible-tmp-1572372537.375614-50462794487074/AnsiballZ_bf_session.py\", line 49, in invoke_module\n    imp.load_module('__main__', mod, module, MOD_DESC)\n  File \"/tmp/ansible_bf_session_payload_LjWdeN/__main__.py\", line 97, in <module>\n  File \"/tmp/ansible_bf_session_payload_LjWdeN/ansible_bf_session_payload.zip/ansible/module_utils/bf_util.py\", line 16, in <module>\n  File \"/opt/venv/ansible-python3/lib/python3.6/site-packages/pybatfish/client/_diagnostics.py\", line 22, in <module>\n    from typing import Any, Dict, Iterable, Optional, TYPE_CHECKING  # noqa: F401\n  File \"/opt/venv/ansible-python3/lib/python3.6/site-packages/typing.py\", line 117\n    def __new__(cls, name, bases, namespace, *, _root=False):\n                                              ^\nSyntaxError: invalid syntax\n",
    "exception": "Traceback (most recent call last):\n  File \"/var/lib/awx/.ansible/tmp/ansible-local-31cdebbdf/ansible-tmp-1572372537.375614-50462794487074/AnsiballZ_bf_session.py\", line 114, in <module>\n    _ansiballz_main()\n  File \"/var/lib/awx/.ansible/tmp/ansible-local-31cdebbdf/ansible-tmp-1572372537.375614-50462794487074/AnsiballZ_bf_session.py\", line 106, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/var/lib/awx/.ansible/tmp/ansible-local-31cdebbdf/ansible-tmp-1572372537.375614-50462794487074/AnsiballZ_bf_session.py\", line 49, in invoke_module\n    imp.load_module('__main__', mod, module, MOD_DESC)\n  File \"/tmp/ansible_bf_session_payload_LjWdeN/__main__.py\", line 97, in <module>\n  File \"/tmp/ansible_bf_session_payload_LjWdeN/ansible_bf_session_payload.zip/ansible/module_utils/bf_util.py\", line 16, in <module>\n  File \"/opt/venv/ansible-python3/lib/python3.6/site-packages/pybatfish/client/_diagnostics.py\", line 22, in <module>\n    from typing import Any, Dict, Iterable, Optional, TYPE_CHECKING  # noqa: F401\n  File \"/opt/venv/ansible-python3/lib/python3.6/site-packages/typing.py\", line 117\n    def __new__(cls, name, bases, namespace, *, _root=False):\n                                              ^\nSyntaxError: invalid syntax\n",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 1,
    "_ansible_no_log": false,
    "changed": false
}
`

Environment details as following below, the playbook is run on an ansible tower in venv.

`
ansible 2.8.6
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /opt/venv/ansible-python3/lib64/python3.6/site-packages/ansible
  executable location = /opt/venv/ansible-python3/bin/ansible
  python version = 3.6.8 (default, Aug  7 2019, 17:28:10) [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]
`

`
(ansible-python3) [root@is-ansible01 ~]# ansible-galaxy info batfish.base
Role: batfish.base
        description: Ansible modules for Batfish (www.batfish.org)
        active: True
        commit: b52e5de59f52b18182eaeffe7b51f69258f61a0a
        commit_message: Use and document new OSPF assert (#83)
        commit_url: https://api.github.com/repos/batfish/ansible/git/commits/b52e5de59f52b18182eaeffe7b51f69258f61a0a
        company:
        created: 2019-06-11T23:55:39.782028Z
        dependencies: []
        download_count: 201
        forks_count: 1
        galaxy_info:
                author: Batfish
                galaxy_tags: ['batfish', 'networking', 'validation']
                license: Apache
                min_ansible_version: 2.7
                role_name: base
        github_branch: master
        github_repo: ansible
        github_user: batfish
        id: 41183
        imported: 2019-09-19T16:45:49.835223-04:00
        install_date: Tue Oct 29 17:05:44 2019
        installed_version: master
        is_valid: True
        issue_tracker_url: https://github.com/batfish/ansible/issues
        license: Apache
        min_ansible_version: 2.7
        modified: 2019-09-19T20:45:49.842435Z
        open_issues_count: 2
        path: ('/root/.ansible/roles', '/usr/share/ansible/roles', '/etc/ansible/roles')
        role_type: ANS
        stargazers_count: 24
        travis_status_url:
`

`
(ansible-python3) [root@is-ansible01 ~]# pip show pybatfish
Name: pybatfish
Version: 0.36.0
Summary: Python API and utilities for Batfish
Home-page: https://github.com/batfish/pybatfish
Author: The Batfish Open Source Project
Author-email: pybatfish-dev@intentionet.com
License: Apache License 2.0
Location: /opt/venv/ansible-python3/lib/python3.6/site-packages
Requires: attrs, deepdiff, deprecated, netconan, pandas, python-dateutil, PyYAML, requests, requests-toolbelt, simplejson, six
Required-by:
`

`
(ansible-python3) [root@is-ansible01 ~]# pip show typing
Name: typing
Version: 3.7.4
Summary: Type Hints for Python
Home-page: https://docs.python.org/3/library/typing.html
Author: Guido van Rossum, Jukka Lehtosalo, Łukasz Langa, Ivan Levkivskyi
Author-email: jukka.lehtosalo@iki.fi
License: PSF
Location: /opt/venv/ansible-python3/lib/python3.6/site-packages
Requires:
Required-by:
`

**Comment by sfraint** [comment]
Hey, thanks for submitting the issue @alkarp, we'll take a look

**Comment by sfraint** [comment]
Closing the loop here: this was an issue with Ansible using a different Python interpreter than expected, which wasn't compatible with some Python3.6 syntax.

From a note [on this page](https://docs.ansible.com/ansible/latest/user_guide/playbooks_delegation.html#local-playbooks):
> If you set the connection to local and there is no ansible_python_interpreter set, modules will run under /usr/bin/python and not under {{ ansible_playbook_python }}. Be sure to set ansible_python_interpreter: “{{ ansible_playbook_python }}” in host_vars/localhost.yml, for example. You can avoid this issue by using `local_action` or `delegate_to: localhost` instead.
